config/routes.rb
Rails.application.routes.draw do
  root "fav_images#index"
  get  "fav_images/new"
  post "fav_images/create"
  delete "fav_images/delete/:id" => "fav_images#destroy"
  get "fav_images/edit/:id" => "fav_images#edit"
  patch "fav_images/edit/:id" => "fav_images#update"

  # bulk
  get  "fav_images/bulk_new"
  post "fav_images/bulk_create"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/fav_image.rb
class FavImage < ApplicationRecord
  has_one_attached :file

  validates :name,
            presence: true
  validates :file,
            presence: true,
            blob: { content_type: :image, size_range: 1..(10.megabytes) }

  before_validation :add_name_if_needed

  def add_name_if_needed
    self.name = file.filename.to_s if name.blank?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/fav_images_controller.rb
class FavImagesController < ApplicationController

  def index
    @fav_images = FavImage.all
  end

  def new
    @fav_image = FavImage.new
  end

  def create
    f = FavImage.create(fav_image_params)
    redirect_to root_path
  end

  def edit
    @fav_image = FavImage.find(params[:id])
  end

  def update
    @fav_image = FavImage.find(params[:id])
    @fav_image.update(fav_image_update_params)
    redirect_to root_path
  end

  def destroy
    FavImage.destroy(params[:id])
    redirect_to root_path
  end

  # Bulk

  def bulk_new
    @fav_image = FavImage.new
  end

  # FIXME: too slow
  def bulk_create
    files = fav_image_bulk_params[:files].reject {|i| i.blank? }
    files.each do |file|
      FavImage.create(file: file)
    end
    redirect_to root_path
  end

  private

  def fav_image_params
    params.require(:fav_image).permit(:name, :file)
  end

  def fav_image_update_params
    params.require(:fav_image).permit(:name)
  end

  def fav_image_bulk_params
    params.require(:fav_image).permit(files: [])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/views/fav_images/bulk_new.html.erb
<section>
  <div class="container">
    <%= form_with model: @fav_image, url: "/fav_images/bulk_create" do |form| %>
    <p>
      <%= form.file_field :files, multiple: true, class: "form-control" %><br>
    </p>
    <%= form.submit "Bulk Upload", class: "btn btn-primary my-2"%>
    <% end %>
  </div>
</section>

app/views/fav_images/edit.html.erb
<div class="album py-5 bg-light">
  <div class="container">

    <div class="row">
      <div class="col-md-4">
        <div class="card mb-4 box-shadow">
          <%= image_tag @fav_image.file, class: "card-img-top" %>
          <div class="card-body">
            <p class="card-text">
              <%= @fav_image.name %>
            </p>
          </div>
        </div>
      </div>

      <%= form_with model: @fav_image, url: "/fav_images/edit/#{@fav_image.id}", method: :patch do |form| %>
          <%= form.text_field :name, class: "form-label", placeholder: "name" %><br>
          <%= form.submit "Update", class: "btn btn-primary my-2"%>
      <% end %>
    </div>
  </div>
</div>

app/views/fav_images/index.html.erb
<div class="album py-5 bg-light">
  <div class="container">

    <div class="row">
      <% @fav_images.each do |fav_image| %>

      <div class="col-md-3">
        <div class="card mb-3 box-shadow">
          <%= image_tag fav_image.file, class: "card-img-top" %>
          <div class="card-body">
            <p class="card-text">
              <%= fav_image.name %>
            </p>
            <div class="d-flex justify-content-between align-items-center">
              <div class="btn-group">
                  <%= button_to "Edit",
                   "fav_images/edit/#{fav_image.id}",
                   {method: :get,
                    id: fav_image.id,
                    class: "btn btn-sm btn-outline-secondary"}
                  %>
                  <%= button_to "Delete",
                   "fav_images/delete/#{fav_image.id}",
                   {method: :delete,
                    id: fav_image.id,
                    form: {data: {turbo_confirm: "Are you sure?"}},
                    class: "btn btn-sm btn-outline-danger"}
                  %>
              </div>
            </div>
          </div>
        </div>
      </div>

      <% end %>
    </div>
  </div>
</div>

app/views/fav_images/new.html.erb
<section>
    <div class="container">
        <%= form_with model: @fav_image, url: "/fav_images/create" do |form| %>
            <p>
                <%= form.file_field :file, class: "form-control" %><br>
                <%= form.text_field :name, class: "form-label", placeholder: "name" %><br>
            </p>
            <%= form.submit "Upload", class: "btn btn-primary my-2"%>
        <% end %>
    </div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FavImageManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>

    <header>
      <div class="navbar navbar-dark bg-dark box-shadow">
        <div class="container d-flex justify-content-between">
          <%= link_to "FavImageManager", root_path, {class: "navbar-brand d-flex align-items-center"} %>
        </div>
      </div>
    </header>

    <main role="main">

      <section class="jumbotron text-center">
        <div class="container">
          <h1 class="jumbotron-heading">Fav Images</h1>
          <p class="lead text-muted">Your favorite images are here!</p>
          <p>
              <%= link_to("Upload FavImage", fav_images_new_path, {class: "btn btn-primary my-2"}) %>
              <%= link_to("Multiple Upload", fav_images_bulk_new_path, {class: "btn btn-secondary my-2"}) %>
          </p>
        </div>
      </section>

      <%= yield %>

    </main>
  </body>
</html>